## Упражнения по библиотеке Numpy

In [6]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [8]:
arr = np.random.randint(-3, 14, size=10)
print("Исходный массив:", arr)

for i in range(len(arr)):
    if 3 <= arr[i] and arr[i] <= 8:
        arr[i] = -arr[i]

print("Результат:", arr)

Исходный массив: [ 7  2  8 -2 -1 -1  0 -2  8  7]
Результат: [-7  2 -8 -2 -1 -1  0 -2 -8 -7]


**2.** Заменить максимальный элемент случайного массива на 0

In [31]:
arr = np.random.randint(-3, 14, size=10)
print("Исходный массив:", arr)

max = np.max(arr)

for i in range(len(arr)):
    if arr[i] == max:
        arr[i] = 0

print("Результат:", arr)

Исходный массив: [ 3 10  4 -3  8 11 -3  4  2  0]
Результат: [ 3 10  4 -3  8  0 -3  4  2  0]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [29]:
arr_1 = np.random.randint(-3, 14, size=(2, 3))
print("Исходный массив номер 1:\n", arr_1)

arr_2 = np.empty((9, 2), dtype=int)

len_1 = len(arr_1[0])
len_2 = len(arr_1[1])

for i in range(len_1):
    for j in range(len_2):
        arr_2[i * len_1 + j][0] = arr_1[0][i]
        arr_2[i * len_1 + j][1] = arr_1[1][j]

print("Результат:\n", arr_2)

Исходный массив номер 1:
 [[-1 13 13]
 [ 0  8 13]]
Результат:
 [[-1  0]
 [-1  8]
 [-1 13]
 [13  0]
 [13  8]
 [13 13]
 [13  0]
 [13  8]
 [13 13]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [35]:
arr_1 = np.random.randint(-3, 14, size=(8, 3))
print("Исходный массив номер 1:\n", arr_1)

arr_2 = np.random.randint(-3, 14, size=(2, 2))
print("Исходный массив номер 2:\n", arr_2)

print("Результат:")
for i in range(len(arr_1)):
    ok = True
    for j in range(len(arr_2)):
        mask = np.isin(arr_1[i], arr_2[j])
        if True not in mask:
            ok = False
    if ok:
        print(arr_1[i])

Исходный массив номер 1:
 [[10 -3  9]
 [ 2  2 -2]
 [12  4  3]
 [11 11  4]
 [-1 -1 13]
 [-3  5  9]
 [ 7  0  4]
 [13  7  4]]
Исходный массив номер 2:
 [[-2 13]
 [ 7 -1]]
Результат:
[-1 -1 13]
[13  7  4]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [49]:
arr_1 = np.random.randint(1, 5, size=(10, 3))
print("Исходный массив номер 1:\n", arr_1)

print("Результат:\n")
for i in range(len(arr_1)):
    first_al = arr_1[i][0]
    ok = True
    for j in range(len(arr_1[i])):
        if arr_1[i][j] != first_al:
            ok = False
    if ok:
        print(arr_1[i])

Исходный массив номер 1:
 [[2 2 4]
 [1 3 2]
 [3 1 1]
 [3 1 4]
 [1 2 2]
 [2 2 1]
 [1 4 2]
 [4 4 4]
 [1 2 1]
 [2 2 2]]
Результат:

[4 4 4]
[2 2 2]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [53]:
arr_1 = np.random.randint(1, 3, size=(10, 3))
print("Исходный массив номер 1:\n", arr_1)

result = np.unique(arr_1, axis=0)
print("Результат:\n", result)

Исходный массив номер 1:
 [[1 1 1]
 [1 1 1]
 [1 2 2]
 [1 1 1]
 [1 1 1]
 [2 1 1]
 [2 1 2]
 [1 2 2]
 [1 1 2]
 [1 2 1]]
Результат:
 [[1 1 1]
 [1 1 2]
 [1 2 1]
 [1 2 2]
 [2 1 1]
 [2 1 2]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [59]:
x_com = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
x_np = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])

#common realization
result = 1
for i in range(min(len(x_com), len(x_com[0]))):
    if x_com[i][i] != 0:
        result *= x_com[i][i]
print("common realization: ", result)

#np realization
diag = np.diagonal(x_np)
nonzero_diag = diag[diag != 0]
prod = np.prod(nonzero_diag)
print("np realization: ", prod)

3
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [62]:
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
x_np = np.array([1, 2, 2, 4])
y_np = np.array([4, 2, 1, 2])

#common realization
same_multiset = x.sort() == y.sort()
print("common realization: ", same_multiset)

#np realization
same_multiset = np.array_equal(np.sort(x_np), np.sort(y_np))
print("np realization: ", same_multiset)

common realization:  True
np realization:  True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [65]:
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
x_np = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

#common realization
max = -1
for i in range(len(x)):
    if i > 0 and x[i - 1] == 0 and x[i] > max:
        max = x[i]
print("common realization: ", max)

#np realization
mask = x_np[:-1] == 0
candidates = x_np[1:][mask]
result = np.max(candidates)
print("np realization: ", result)

common realization:  5
np realization:  5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [81]:
x = [2, 2, 2, 3, 3, 3, 5]
x_np = np.array([2, 2, 2, 3, 3, 3, 5])

#common realization
y_val = []
y_count = []
previous = x[0]
count = 1
for i in range(1, len(x)):
    if x[i] != previous or i == len(x) - 1:
        y_val.append(previous)
        y_count.append(count)
        previous = x[i]
        count = 1
    else:
        count += 1
y_val.append(previous)
y_count.append(count)
print("common realization: ", y_val, y_count)

#np realization
changes = np.where(np.diff(x_np) != 0)[0] + 1
counts = np.diff(np.concatenate(([0], changes, [x_np.size])))
values = x_np[np.concatenate(([0], changes))]
print("np realization: ", values, counts)

common realization:  [2, 3, 5] [3, 3, 1]
np realization:  [2 3 5] [3 3 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [8]:
from scipy.spatial.distance import cdist
import time

X = np.random.rand(2000, 50)
Y = np.random.rand(2000, 50)

#scipy realization

t0 = time.time()
D_scipy = cdist(X, Y, metric='euclidean')
t_scipy = time.time() - t0

print("scipy realization: \n", D_scipy)
print(t_scipy)

#np realization
def euclidean_distance_matrix(X, Y):
    X_sq = np.sum(X**2, axis=1, keepdims=True)   # (n, 1)
    Y_sq = np.sum(Y**2, axis=1, keepdims=True).T # (1, m)
    distances_sq = X_sq + Y_sq - 2 * X @ Y.T
    return np.sqrt(np.maximum(distances_sq, 0.0))

t0 = time.time()
D_numpy = euclidean_distance_matrix(X, Y)
t_numpy = time.time() - t0
    
print("np realization: \n", D_numpy)
print(t_numpy)

scipy realization: 
 [[2.79323926 2.97534647 3.15742294 ... 3.43933614 2.75711807 3.38450931]
 [3.00199737 2.93523817 2.54226731 ... 3.06170678 2.90548669 3.17340516]
 [2.84026687 2.66556068 2.75867282 ... 2.87641524 2.75453313 3.02098407]
 ...
 [2.56288674 2.79197547 2.90345066 ... 3.08191765 2.87631975 3.19597336]
 [2.66193343 2.3533819  2.58182319 ... 2.96060765 2.41692411 2.69818516]
 [3.11890093 2.7617475  2.75942277 ... 2.8205154  2.85984551 2.96059269]]
0.0523679256439209
np realization: 
 [[2.79323926 2.97534647 3.15742294 ... 3.43933614 2.75711807 3.38450931]
 [3.00199737 2.93523817 2.54226731 ... 3.06170678 2.90548669 3.17340516]
 [2.84026687 2.66556068 2.75867282 ... 2.87641524 2.75453313 3.02098407]
 ...
 [2.56288674 2.79197547 2.90345066 ... 3.08191765 2.87631975 3.19597336]
 [2.66193343 2.3533819  2.58182319 ... 2.96060765 2.41692411 2.69818516]
 [3.11890093 2.7617475  2.75942277 ... 2.8205154  2.85984551 2.96059269]]
0.03305697441101074


* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [77]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [170]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [95]:
calorie_stats_sum = np.sum(calorie_stats)
calorie_stats_count = np.size(calorie_stats)
calorie_stats_avg = calorie_stats_sum / calorie_stats_count
calorie_stats_diff = abs(calorie_stats_avg - 60)

print(calorie_stats_diff)

46.883116883116884


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [92]:
calorie_stats_sorted = np.sort(calorie_stats)

print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [93]:
calorie_stats_median = np.median(calorie_stats)

print(calorie_stats_median)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [118]:
i = 0.0
nth_percentile = 0
while nth_percentile < 60:
    i += 0.1
    nth_percentile = np.percentile(calorie_stats, i)

print(i)

3.3000000000000016


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [119]:
i = 0.0
nth_percentile = 0
while nth_percentile < 60:
    i += 0.1
    nth_percentile = np.percentile(calorie_stats, i)

more_calories = 100 - i
print(more_calories)

96.7


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [120]:
calorie_std = np.std(calorie_stats)

print(calorie_std)

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [167]:
Все эти данные можно использовать для того чтобы показать, что CrunchieMunchies содержит в себе наименьшее количество калорий(наиболее диетические)